Loc["cn"] = {
	["common"] = { --commonly used strings
		owned = "无法改装没有车主的车",
		close = "关闭",
		ret = "返回",
		stock = "原厂", -- Default, Original, whatever word you use for this
		current = "当前已安装",
		noOptions = "此项目没有可用选项",
		installing = "安装",
		amountoption = "可用数量: ",
		already = "已安装", -- eg. "Stock Bumper already Installed"
		menuinstalled = " 个等级] 已安装: ", --eg "[4 Options] Installed: Grille 1"
		nearwheel = "你需要靠近一个车轮",
		nearengine = "你需要靠近引擎"
	},
	--Performance Items
	["armour"] = { --armour.lua
		cant = "这辆车无法安装车辆护甲",
		already = "车辆护甲已安装",
		install = "安装车辆护甲中..",
		installed = "车辆护甲已安装..",
		failed = "车辆护甲安装失败!",
		remove = "车辆护甲已移除",
		removing = "移除车辆护甲..",
		remfail = "车辆护甲移除失败!",
	},
	["brakes"] = { --brakes.lua
		cant = "这辆车无法升级刹车套件",
		already = "刹车升级已经安装过了",
		install = "安装刹车升级套件: ",
		installed = "刹车升级成功..",
		failed = "刹车升级失败!",
		remove = "刹车升级已移除",
		removing = "移除刹车升级套件..",
		remfail = "移除刹车升级套件失败!",
	},
	["engines"] = { --engines.lua
		cant = "这辆车无法升级引擎套件",
		already = "引擎升级已经安装过了",
		install = "安装引擎升级套件: ",
		installed = "引擎升级成功..",
		failed = "引擎升级失败!",
		remove = "引擎升级已移除",
		removing = "移除引擎升级套件..",
		remfail = "移除引擎升级套件失败!",
	},
	["suspension"] = { --suspension.lua
		cant = "这辆车无法升级避震套件",
		already = "避震升级已经安装过了",
		install = "安装避震升级套件: ",
		installed = "避震升级成功..",
		failed = "避震升级失败!",
		removed = "避震升级已移除",
		removing = "移除避震升级套件..",
		remfail = "移除避震升级套件失败!",
	},
	["transmission"] = { --transmission.lua
		cant = "这辆车无法升级变速箱套件",
		already = "变速箱升级已经安装过了",
		install = "安装变速箱升级套件: ",
		installed = "变速箱升级成功..",
		failed = "变速箱升级失败!",
		remove = "变速箱升级已移除",
		removing = "移除变速箱升级套件..",
		remfail = "移除变速箱升级套件失败!",
	},
	["tires"] = { --tires.lua
		--Drift
		already = "漂移轮胎已经安装过了",
		install = "安装漂移轮胎..",
		installed = "漂移轮胎安装成功",
		failed = "漂移轮胎安装失败!",
		remove = "漂移轮胎已移除",
		removing = "移除漂移轮胎..",
		remfail = "移除漂移轮胎失败!",
		swap = "防弹轮胎已移除!",
		--BProof
		already2 = "防弹轮胎已经安装过了",
		install2 = "安装防弹轮胎..",
		installed2 = "防弹轮胎安装成功",
		failed2 = "防弹轮胎安装失败!",
		remove2 = "防弹轮胎已移除",
		removing2 = "移除防弹轮胎",
		remfail2 = "移除防弹轮胎失败!",
		swap2 = "漂移轮胎已移除!",
	},
	["turbo"] = { --turbo.lua
		already = "涡轮增压器已经安装过了",
		install = "安装涡轮增压器..",
		installed = "涡轮增压器安装成功..",
		failed = "涡轮增压器安装失败!",
		remove = "涡轮增压器已移除",
		removing = "移除涡轮增压器..",
		remfail = "移除涡轮增压器失败!",
	},
	["xenons"] = { --xenons.lua
		already = "氙气灯已经安装过了",
		install = "安装氙气灯..",
		installed = "氙气灯安装成功",
		failed = "氙气灯安装失败!",
		remove = "氙气灯已移除",
		removing = "移除氙气灯..",
		remfail = "移除氙气灯失败!",
		closer = "靠近大灯",

		notinstall = "未安装氙气灯",
		--Menus
		neonheader1 = "氙气灯控制",
		neonheader2 = "车底灯控制",
		neonheader3 = "车底灯颜色控制",
		neonheader4 = "氙气灯控制",
		customheader = "自定义RBG",
		customconfirm = "提交",
		neontxt1 = "霓虹灯细节控制",
		toggle = "切换全部",
		front = "前侧",
		right = "右侧",
		left = "左侧",
		back = "后侧",
		neontxt2 = "更改车底灯颜色",
		xenonheader = "氙气灯控制",
		xenontxt = "调整车头灯颜色",
	},

	--Cosmetic Items
	["bumpers"] = { --bumpers.lua
		stockMod = "原厂保险杠..",
		installed = "保险杠安装成功",
		failed = "保险杠安装失败!",
		menuheader = " 中网和保险杠改装", --eg "Sultan RS Grille and Bumper Cosmetics"
		menugrille = "中网",
		menuFBumper = "前保险杠",
		menuBBumper = "后保险杠",
	},
	["exhaust"] = { --exhaust.lua
		stockMod = "原厂排气..",
		already = "已安装", -- eg. "Stock Bumper already Installed"
		installed = "排气安装成功",
		failed = "排气安装失败!",
		menuheader = " 排气改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["exterior"] = { --exterior.lua
		stockMod = "原厂外观..",
		installed = "外观部件安装成功",
		failed = "外观部件安装失败!",
		menuheader = " 外观部件改装", --eg "Sultan RS Grille and Bumper Cosmetics"

		label1 = "部件A",
		label2 = "部件B",
		label3 = "后备箱",
		label4 = "发动机缸体",
		label5 = "空气滤网",
		label6 = "发动机构型",
		label7 = "液压泵",
		label8 = "灯罩",
		label9 = "油箱",
		label10 = "天线",
	},
	["hood"] = { --hood.lua
		stockMod = "原厂引擎盖..",
		installed = "引擎盖安装成功",
		failed = "引擎盖安装失败!",
		menuheader = " 引擎盖改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["horns"] = { --horns.lua
		installed = "喇叭安装成功",
		failed = "喇叭安装失败!",
		menuheader = " 喇叭改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["interior"] = { --interior.lua
		stockMod = "原厂内饰..",
		installed = "内饰部件安装成功",
		failed = "内饰部件安装失败!",
		menuheader = " 内饰部件改装", --eg "Sultan RS Grille and Bumper Cosmetics"

		label1 = "防滚架",
		label2 = "装饰品",
		label3 = "仪表台",
		label4 = "仪表盘",
		label5 = "车门音响",
		label6 = "方向盘",
		label7 = "换挡杆",
		label8 = "装饰牌",
		label9 = "音响",
	},
	["livery"] = { --exhaust.lua
		oldMod = "旧的",
		already = " 已安装", -- eg. "Stock Bumper already Installed"
		installed = "涂装安装成功",
		failed = "涂装安装失败!",
		menuheader = " 涂装改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["nos"] = { --exhaust.lua
		notinstalled = "未安装涡轮增压器",
		installing = "NOS安装中..",
		installed = "NOS安装成功",
		failed = "NOS安装失败!",
		removing = "移除NOS罐",
		removed = "NOS罐已移除",
		remfail = "NOS罐移除失败!",
		nosColour = "氮气喷射颜色",
		boostmode = "加速模式",
		purgemode = "喷射模式",
		boost = "加速强度: ",
		spray = "喷射强度: ",
	},
	["paint"] = { --paints.lua
		primary = "主色调",
		secondary = "副色调",
		pearl = "珠光颜色",
		wheel = "轮圈颜色",
		dashboard = "仪表颜色",
		interior = "内饰颜色",

		classic = "经典色",
		metallic = "仿金属色",
		matte = "哑光",
		metals = "金属色",
		chameleon = "渐变色",

		installing = "更改喷漆颜色中..",
		installed = "喷漆颜色更改成功",
		failed = "喷漆颜色更改失败!",
		menuheader = " 喷漆",
	},
	["paintrgb"] = {
		select = "色调:",
		finish = "材质:",
		error = "Hex值最少是6个字符",
		customheader = "自定义颜色",
		chrome = "铬合金",
		hex = "HEX输入",
		rgb = "RGB输入",
	},
	["plates"] = { --paints.lua
		already = "牌照已安装!",
		installing = "安装牌照中..",
		installed = "牌照安装成功",
		failed = "牌照安装失败!",
		menuheader = " 牌照改装",
		label1 = "牌照架",
		label2 = "牌照背景",
		label3 = "牌照DIY",
		menuheader2 = " 牌照背景风格",
	},
	["rims"] = {
		installing = "安装轮圈中..",
		installed = "轮圈安装成功",
		failed = "轮圈安装失败!",
		menuheader = "轮圈改装",

		label1 = "运动",
		label2 = "肌肉",
		label3 = "跳跳",
		label4 = "SUV",
		label5 = "越野",
		label6 = "改装",
		label7 = "高端",
		label8 = "班尼原创",
		label9 = "班尼定制",
		label10 = "开放",
		label11 = "街头",
		label12 = "赛道",
		label13 = "前轮",
		label14 = "后轮",
		label15 = "摩托",

		labelcustom = "自定义轮圈",
	},
	["rollcage"] = { --rollcage.lua
		installed = "防滚架安装成功!",
		failed = "防滚架安装失败!",
		menuheader = "防滚架改装",
	},
	["roof"] = { --roof.lua
		installed = "车棚安装成功",
		failed = "车棚安装失败!",
		menuheader = " 车棚改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["seat"] = { --seat.lua
		installed = "车座安装成功",
		failed = "车座安装失败!",
		menuheader = " 车座改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["skirts"] = { --skirts.lua
		installed = "侧裙安装成功",
		failed = "侧裙安装失败!",
		menuheader = " 侧裙和叶子板改装", --eg "Sultan RS Grille and Bumper Cosmetics"
		menuskirt = "侧裙",
		menuRF = "右侧叶子板",
		menuLF = "左侧叶子板",
	},
	["spoilers"] = { --spoilers.lua
		installed = "尾翼安装成功",
		failed = "尾翼安装失败!",
		menuheader = " 尾翼改装", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["smoke"] = { --tiresmoke.lua
		already = "这个颜色当前已经在使用了!",
		installing = "更改车轮烟雾颜色..",
		installed = "车轮烟雾更改成功",
		failed = "车轮烟雾更改失败!",
		menuheader = " 车轮烟雾改装", --eg "Sultan RS Grille and Bumper Cosmetics"

		remove = "移除烟雾",
		custom = "自定义RBG",
		black = "黑色",
		white = "白色",
		blue = "蓝色",
		eblue = "电子蓝",
		mgreen = "青绿色",
		lgreen = "翠绿色",
		yellow = "黄色",
		gshower = "金色",
		orange = "橙色",
		red = "红色",
		ppink = "小马粉",
		hpink = "热粉",
		purple = "紫色",
		blacklight = "黑光",

		submit = "提交",
	},
	["windows"] = { --windows.lua
		installed = "玻璃膜安装成功",
		failed = "玻璃膜安装失败!",
		menuheader = " 玻璃膜", --eg "Sultan RS Grille and Bumper Cosmetics"

		label1 = "移除",
		label2 = "透明",
		label3 = "绿",
		label4 = "淡雾",
		label5 = "黑雾",
		label6 = "纯黑",
	},
	["stores"] = {
		browse = "查看商店",
		tools = "技工工具",
		perform = "性能升级套件",
		cosmetic = "改装零件",
	},
	["crafting"] = { --crafting.lua
		menuheader = "技工制作",
		toolheader = "技工工具",
		performheader = "性能升级套件",
		cosmetheader = "改装零件",
		numitems = " 个物品", --for menu. eg. "11 items"
		ingredients = "你没有正确的原材料",
	},
	["payments"] = { --payments.lua
		charge = "向客户收费",
	},
	["check"] = { --check_tunes.lua
		plate = "车牌号: [",
		value = "]<br>价值: $",
		unavail = "❌ 不可用",
		notinstall = "未安装",
		reinforced = "车身已强化",
		xenoninst = "氙气灯已安装",
		tireinst = "已安装",

		label1 = "引擎:",
		label2 = "刹车:",
		label3 = "避震:",
		label4 = "变速箱:",
		label5 = "护甲:",
		label6 = "涡轮增压器:",
		label7 = "氙气灯:",
		label8 = "漂移轮胎:",
		label9 = "防弹轮胎:",
		label10 = "可改装的配件清单",
		label11 = "车辆: ",

		label12 = " 个选项 ]",
		label13 = "- 外观部件 -",
		label14 = "- 内饰部件 - ",
		label15 = "尾翼 - [ ",
		label16 = "前保险杠 - [ ",
		label17 = "后保险杠 - [ ",
		label18 = "侧裙 - [ ",
		label19 = "排气管 - [ ",
		label20 = "中网 - [ ",
		label21 = "引擎盖 - [ ",
		label22 = "左叶子板 - [ ",
		label23 = "右叶子板 - [ ",
		label24 = "车棚 - [ ",
		label25 = "牌照架 - [ ",
		label26 = "牌照背景 - [ ",
		label27 = "内饰部件A - [ ",
		label28 = "内饰部件B - [ ",
		label29 = "后备箱 - [ ",
		label30 = "发动机缸体 - [ ",
		label31 = "空气滤网 - [ ",
		label32 = "发动机构型 - [ ",
		label33 = "灯罩 - [ ",

		label34 = "防滚架 - [ ",
		label35 = "装饰品 - [ ",
		label36 = "仪表台 - [ ",
		label37 = "仪表盘 - [ ",
		label38 = "车门音响 - [ ",
		label39 = "座椅 - [ ",
		label40 = "方向盘 - [ ",
		label41 = "换挡杆 - [ ",
		label42 = "装饰牌 - [ ",
		label43 = "音响 - [ ",
		label44 = "液压泵 - [ ",
		label45 = "天线 - [ ",
		label46 = "油箱 - [ ",
		label47 = "是",
		label48 = "否",
		label49 = "你是否确认要移除刹车套件?",
		label50 = "你是否确认要移除引擎套件?",
		label51 = "你是否确认要移除避震套件?",
		label52 = "你是否确认要移除变速箱套件?",
		label53 = "你是否确认要移除护甲?",
		label54 = "你是否确认要移除涡轮增压器?",
		label55 = "你是否确认要移除氙气灯?",
		label56 = "你是否确认要移除轮胎?",
		label57 = "你是否确认要移除氮气?",
		label58 = "氮气:",
	},
	["repair"] = {
		browse = "查看仓库",
		materials = "你没有足够的材料",
		checkeng = "查看引擎受损状况..",
		checkbody = "查看车体受损状况..",

		engine = "引擎",
		body = "车体",
		radiator = "散热器",
		driveshaft = "传动轴",
		brakes = "刹车",
		clutch = "离合器",
		tank = "油箱k",
		replacetire = "更换轮胎",
		tire = "车轮",

		repairing = "正在修理",
		changing = "更换中 ",
		repaired = "完全修复",
		cancel = "修复取消!",
		nomaterials = "仓库里没有足够的材料",
		failinfo = "获取车辆信息失败, 请再次尝试使用工具箱",

		cost = "<br>花费: ",
		status = "状态: ",
		doyou = "你是否想修理",

		applyduct = "用胶带修复..",
		ductfull = "你不能在这辆车上用更多的胶带了",
		nocar = "附近没有车啊",
	},
	["police"] = {
		userepair = "使用修理站",
		repair = "修理",
		extras = "配件",
		plates = "车牌",
		livery = "涂装",
		spoiler = "尾翼",
		cleaning = "车辆清洗中...",
		engine = "引擎修复中...",
		body = "车体修复中...",
		complete = "车辆修复完成",
	},
	["manual"] = {
		tyres = "更换破损轮胎中",
		window = "移除破损车窗中",
		doors = "车门修复中",
	},
	["carwax"] = {
		head1 = "清洗车辆",
		head2 = "清洗和打蜡",
		head3 = "清洗和高级打蜡",
		head4 = "清洗和终极打蜡",
	},
	["extras"] = {
		clean = "车辆清理",
		doorerr = "车门错误",
		locked = "车门已锁",
		flipping = "翻车恢复",
		flipped = "翻车恢复成功",
		failed = "翻车恢复失败!",
		noseat = "未输入座位号",
		moveseat = "你移到了座位",
		fastseat = "这辆车开的太快了..",
		notseat = "这个座位不可用..",
		harness = "你正用着赛车安全带不能换座..",
	},
	["functions"] = {
		distance = "行驶里程: ",
		inCar = "不能在车内这么做",
		outCar = "只有在车内才能这么做",
		locked = "车辆已上锁",
		nearby = "附近没有车啊",
		shop = "不能在店外工作",
		mechanic = "只有修理技工知道该怎么做",
	},
	["servfunction"] = {
		checkdamage = "查看车辆受损状况",
		checkmods = "查看车辆可用的改装件",
		flipvehicle = "翻转最近的车辆",
		togglesound = "开启升级引擎声",
		togglesoundesc = "设置引擎声开关",
		cleancar = "清理车辆",
		hood = "开/关 引擎盖",
		trunk = "开/关 后备箱",
		door = "开/关 车门 [0-3]",
		seat = "换座位 [-1 到 10]",
	},
	["previews"] = {
		changes = "改装项目: ",
	},
	["garage"] = {
		jobgarage = "公共车库",
		vehout = "车辆已出库",
		remveh = "移除车辆",
		cantspawn = " 挡住了",
		marker = "工作车辆已在地图上标记",
		markername = "工作车辆",
	},
	--Below are names of items/mods that can't be reteived natively
	vehiclePlateOptions = {
		{ name = "白底蓝字#1", id = 0 },
		{ name = "白底蓝字#2", id = 3 },
		{ name = "白底蓝字#3", id = 4 },
		{ name = "蓝底黄字", id = 2 },
		{ name = "黑底黄字", id = 1 },
		{ name = "北扬克顿", id = 5 },
	},
	vehicleNeonOptions = {
		{ name = "白色", R = 255, G = 255, B = 255 },
        { name = "蓝色", R = 2, G = 21, B = 255 },
        { name = "电子蓝", R = 3, G = 83, B = 255 },
        { name = "青绿色", R = 0, G = 255, B = 140 },
        { name = "翠绿色", R = 94, G = 255, B = 1 },
        { name = "黄色", R = 255, G = 255, B = 0 },
        { name = "金色", R = 255, G = 150, B = 0 },
        { name = "橙色", R = 255, G = 62, B = 0 },
        { name = "红色", R = 255, G = 1, B = 1 },
        { name = "小马粉", R = 255, G = 50, B = 100 },
        { name = "热粉", R = 255, G = 5, B = 190 },
        { name = "紫色", R = 35, G = 1, B = 255 },
        { name = "黑光", R = 15, G = 3, B = 255 }
	},
	vehicleHorns = {
		{ name = "汽笛", id = 0 },
		{ name = "警笛", id = 1 },
		{ name = "小丑喇叭", id = 2 },
		{ name = "音乐号角 1", id = 3 },
		{ name = "音乐号角 2", id = 4 },
		{ name = "音乐号角 3", id = 5 },
		{ name = "音乐号角 4", id = 6 },
		{ name = "音乐号角 5", id = 7 },
		{ name = "悲伤的长号", id = 8 },
		{ name = "古典号角 1", id = 9 },
		{ name = "古典号角 2", id = 10 },
		{ name = "古典号角 3", id = 11 },
		{ name = "古典号角 4", id = 12 },
		{ name = "古典号角 5", id = 13 },
		{ name = "古典号角 6", id = 14 },
		{ name = "古典号角 7", id = 15 },
		{ name = "音阶 - Do", id = 16 },
		{ name = "音阶 - Re", id = 17 },
		{ name = "音阶 - Mi", id = 18 },
		{ name = "音阶 - Fa", id = 19 },
		{ name = "音阶 - Sol", id = 20 },
		{ name = "音阶 - La", id = 21 },
		{ name = "音阶 - Ti", id = 22 },
		{ name = "音阶 - Do", id = 23 },
		{ name = "爵士号角 1", id = 24 },
		{ name = "爵士号角 2", id = 25 },
		{ name = "爵士号角 3", id = 26 },
		{ name = "爵士号角循环", id = 27 },
		{ name = "星条旗 1", id = 28 },
		{ name = "星条旗 2", id = 29 },
		{ name = "星条旗 3", id = 30 },
		{ name = "星条旗 4", id = 31 },
		{ name = "古典号角 8循环", id = 32 },
		{ name = "古典号角 9循环", id = 33 },
		{ name = "古典号角 10循环", id = 34 },
		{ name = "古典号角 8", id = 35 },
		{ name = "古典号角 9", id = 36 },
		{ name = "古典号角 10", id = 37 },
		{ name = "葬礼", id = 38 },
		{ name = "葬礼", id = 39 },
		{ name = "幽灵循环", id = 40 },
		{ name = "幽灵", id = 41 },
		{ name = "圣安地列斯循环", id = 42 },
		{ name = "圣安地列斯", id = 43 },
		{ name = "自由城循环", id = 44 },
		{ name = "自由城", id = 45 },
		{ name = "庆典 1循环", id = 46 },
		{ name = "庆典 1", id = 47 },
		{ name = "庆典 2循环", id = 48 },
		{ name = "庆典 2", id = 49 },
		{ name = "庆典 3循环", id = 50 },
		{ name = "庆典 3", id = 51 },
		{ name = "汽笛 1循环", id = 52},
		{ name = "汽笛 1", id = 53},
		{ name = "汽笛 2循环", id = 54},
		{ name = "汽笛 2", id = 55},
		{ name = "汽笛 3循环", id = 56},
		{ name = "汽笛 3", id = 57},
	},
	vehicleResprayOptionsClassic = {
		{ name = "黑色", id = 0 },
		{ name = "炭黑色", id = 147 },
		{ name = "石墨黑", id = 1 },
		{ name = "煤黑色", id = 11 },
		{ name = "黑钢色", id = 2 },
		{ name = "暗钢色", id = 3 },
		{ name = "银色", id = 4 },
		{ name = "蓝银", id = 5 },
		{ name = "轧钢色", id = 6 },
		{ name = "暗影银", id = 7 },
		{ name = "石银色", id = 8 },
		{ name = "午夜银", id = 9 },
		{ name = "铸铁银", id = 10 },
		{ name = "红色", id = 27 },
		{ name = "都灵红", id = 28 },
		{ name = "方程式红", id = 29 },
		{ name = "熔岩红", id = 150 },
		{ name = "火焰红", id = 30 },
		{ name = "优雅红", id = 31 },
		{ name = "石榴红", id = 32 },
		{ name = "日落红", id = 33 },
		{ name = "赤霞珠红", id = 34 },
		{ name = "酒红", id = 143 },
		{ name = "糖果红", id = 35 },
		{ name = "亮粉色", id = 135 },
		{ name = "菲斯特粉", id = 137 },
		{ name = "三文鱼粉", id = 136 },
		{ name = "日出橙", id = 36 },
		{ name = "橙色", id = 38 },
		{ name = "亮橙色", id = 138 },
		{ name = "金色", id = 99 },
		{ name = "铜色", id = 90 },
		{ name = "黄色", id = 88 },
		{ name = "赛车黄", id = 89 },
		{ name = "露水黄", id = 91 },
		{ name = "暗绿色", id = 49 },
		{ name = "赛车绿", id = 50 },
		{ name = "海绿色", id = 51 },
		{ name = "橄榄绿", id = 52 },
		{ name = "亮绿色", id = 53 },
		{ name = "汽油绿", id = 54 },
		{ name = "翠绿色", id = 92 },
		{ name = "午夜蓝", id = 141 },
		{ name = "星空蓝", id = 61 },
		{ name = "暗蓝色", id = 62 },
		{ name = "撒克逊蓝", id = 63 },
		{ name = "蓝色", id = 64 },
		{ name = "水手蓝", id = 65 },
		{ name = "海港蓝", id = 66 },
		{ name = "钻石蓝", id = 67 },
		{ name = "冲浪蓝", id = 68 },
		{ name = "航海蓝", id = 69 },
		{ name = "赛车蓝", id = 73 },
		{ name = "超蓝", id = 70 },
		{ name = "亮蓝", id = 74 },
		{ name = "巧克力棕", id = 96 },
		{ name = "野牛棕", id = 101 },
		{ name = "克里恩棕", id = 95 },
		{ name = "费尔策棕", id = 94 },
		{ name = "枫棕色", id = 97 },
		{ name = "榉木棕", id = 103 },
		{ name = "赭棕", id = 104 },
		{ name = "马鞍棕", id = 98 },
		{ name = "泥沼棕", id = 100 },
		{ name = "榉棕", id = 102 },
		{ name = "稻草棕", id = 99 },
		{ name = "沙棕色", id = 105 },
		{ name = "漂棕色", id = 106 },
		{ name = "谢弗紫", id = 71 },
		{ name = "三角帆紫", id = 72 },
		{ name = "午夜紫", id = 142 },
		{ name = "亮紫色", id = 145 },
		{ name = "奶油色", id = 107 },
		{ name = "冰白", id = 111 },
		{ name = "霜白", id = 112 },
	},
	vehicleResprayOptionsMatte = {
		{ name = "黑色", id = 12 },
		{ name = "灰色", id = 13 },
		{ name = "亮灰色", id = 14 },
		{ name = "冰白", id = 131 },
		{ name = "蓝色", id = 83 },
		{ name = "暗蓝色", id = 82 },
		{ name = "午夜蓝", id = 84 },
		{ name = "午夜紫", id = 149 },
		{ name = "谢弗紫", id = 148 },
		{ name = "红色", id = 39 },
		{ name = "暗红色", id = 40 },
		{ name = "橙色", id = 41 },
		{ name = "黄色", id = 42 },
		{ name = "翠绿色", id = 55 },
		{ name = "绿色", id = 128 },
		{ name = "森林绿", id = 151 },
		{ name = "叶绿色", id = 155 },
		{ name = "橄榄色", id = 152 },
		{ name = "黑暗地球", id = 153 },
		{ name = "沙漠棕褐色", id = 154 },
	},
	vehicleResprayOptionsMetals = {
		{ name = "拉丝钢", id = 117 },
		{ name = "拉丝黑钢", id = 118 },
		{ name = "拉丝铝", id = 119 },
		{ name = "纯金色", id = 158 },
		{ name = "拉丝金", id = 159 },
		{ name = "铬合金", id = 120 },
	},
	vehicleResprayOptionsChameleon = {
		{ name = "黑白", id = 223 },
		{ name = "色差", id = 236 },
		{ name = "昼夜", id = 224 },
		{ name = "维利尔", id = 225 },
		{ name = "极度斯普朗克", id = 226 },
		{ name = "罪恶都市", id = 227 },
		{ name = "日落", id = 233 },
		{ name = "温差", id = 238 },
		{ name = "震波之夜", id = 228 },
		{ name = "四季", id = 229 },
		{ name = "老七", id = 234 },
		{ name = "复古别墅", id = 230 },
		{ name = "泡泡堂", id = 231 },
		{ name = "彩虹", id = 232 },
		{ name = "假面骑士", id = 235 },
		{ name = "圣诞节", id = 237 },
	},
}
