Loc["da"] = {
	["common"] = { -- Almindeligt anvendte strenge
		owned = "Køretøjet ejes ikke, kan ikke ændres",
		close = "Luk",
		ret = "Tilbage",
		stock = "Standard", -- Standard, Original, hvad end du bruger for dette
		current = "Installeret i øjeblikket",
		noOptions = "Ingen muligheder tilgængelige for denne genstand",
		installing = "Installerer ",
		amountoption = "Antal muligheder: ",
		already = " allerede installeret", -- f.eks. "Standard Kofanger allerede Installeret"
		menuinstalled = " Muligheder] Installeret: ", -- f.eks. "[4 Muligheder] Installeret: Kølergitter 1"
		nearwheel = "Du skal komme tættere på et hjul",
		nearengine = "Du skal komme tættere på motoren"
	},
	-- Ydelsesgenstande
	["armour"] = { -- armour.lua
		cant = "Panser kan ikke installeres på dette køretøj",
		already = "Panser allerede installeret",
		install = "Installerer panser..",
		installed = "Succes! Panser installeret..",
		failed = "Fejl i panserinstallation!",
		removed = "Succes! Panser fjernet",
		removing = "Fjerner panser..",
		remfail = "Fejl i fjernelse af panser!",
	},
	["brakes"] = { -- brakes.lua
		cant = "Bremser kan ikke installeres på dette køretøj",
		already = "Bremser allerede installeret",
		install = "Installerer bremser niveau: ",
		installed = "Succes! Bremser installeret..",
		failed = "Fejl i bremseinstallation!",
		remove = "Succes! Bremser fjernet",
		removing = "Fjerner bremser..",
		remfail = "Fejl i fjernelse af bremser!",
	},
	["engines"] = { -- engines.lua
		cant = "Motorer kan ikke installeres på dette køretøj",
		already = "Motoren allerede installeret",
		install = "Installerer motor niveau: ",
		installed = "Succes! Motor installeret..",
		failed = "Fejl i motorinstallation!",
		remove = "Succes! Motor fjernet",
		removing = "Fjerner motor..",
		remfail = "Fejl i fjernelse af motor!",
	},
	["suspension"] = { -- suspension.lua
		cant = "Undervogn kan ikke installeres på dette køretøj",
		already = "Undervogn allerede installeret",
		install = "Installerer Undervogn Niveau: ",
		installed = "Succes! Undervogn Installeret..",
		failed = "Undervogn installation mislykkedes!",
		removed = "Succes! Undervogn fjernet",
		removing = "Fjerner Undervogn..",
		remfail = "Fejl i fjernelse af undervogn!",
	},
	["transmission"] = { -- transmission.lua
		cant = "Transmission kan ikke installeres på dette køretøj",
		already = "Transmission allerede installeret",
		install = "Installerer Transmission Niveau: ",
		installed = "Succes! Transmission Installeret..",
		failed = "Transmission installation mislykkedes!",
		remove = "Succes! Transmission fjernet",
		removing = "Fjerner Transmission..",
		remfail = "Fejl i fjernelse af transmission!",
	},
	["tires"] = { -- tires.lua
		-- Drift
		already = "Drift Dæk allerede installeret",
		install = "Installerer Drift Dæk..",
		installed = "Succes! Drift Dæk Installeret",
		failed = "Drift Dæk installation mislykkedes!",
		remove = "Succes! Drift Dæk fjernet",
		removing = "Fjerner Drift Dæk..",
		remfail = "Fejl i fjernelse af drift dæk!",
		swap = "Bulletproof Dæk fjernet!",
		-- BulletProof
		already2 = "Bulletproof Dæk allerede installeret",
		install2 = "Installerer Bulletproof Dæk..",
		installed2 = "Succes! Bulletproof Dæk Installeret",
		failed2 = "Bulletproof Dæk installation mislykkedes!",
		remove2 = "Succes! Bulletproof Dæk fjernet",
		removing2 = "Fjerner Bulletproof Dæk",
		remfail2 = "Fejl i fjernelse af bulletproof dæk!",
		swap2 = "Drift Dæk fjernet!",
	},
	["turbo"] = { -- turbo.lua
		already = "Turbo allerede installeret",
		install = "Installerer Turbo..",
		installed = "Succes! Turbo Installeret..",
		failed = "Turbo installation mislykkedes!",
		remove = "Succes! Turbo fjernet",
		removing = "Fjerner Turbo..",
		remfail = "Fejl i fjernelse af turbo!",
	},
	["xenons"] = { -- xenons.lua
		already = "Xenon Forlygter allerede installeret",
		install = "Installerer Xenon..",
		installed = "Succes! Xenon Forlygter Installeret",
		failed = "Xenon Forlygter installation mislykkedes!",
		remove = "Succes! Xenon fjernet",
		removing = "Fjerner Xenon..",
		remfail = "Fejl i fjernelse af xenon!",
		closer = "Kom tættere på forlygterne",
		notinstall = "Xenon Forlygter Ikke Installeret",
		-- Menuer
		neonheader1 = "Lyskontrol",
		neonheader2 = "Underglødelys Kontrol",
		neonheader3 = "Underglødefarve Kontrol",
		neonheader4 = "Xenon Forlygter Kontrol",
		customheader = "Brugerdefineret RBG",
		customconfirm = "ANVEND",
		neontxt1 = "Præcis kontrol af Neonbelysning",
		toggle = "Skift ALLE",
		front = "Foran",
		right = "Højre",
		left = "Venstre",
		back = "Bagpå",
		neontxt2 = "Skift Underglødefarve",
		xenonheader = "Xenon Kontrol",
		xenontxt = "Justér køretøjets forlygterfarve",
	},
	-- Kosmetiske genstande
	["bumpers"] = { -- bumpers.lua
		stockMod = "Standard Kofanger..",
		installed = "Succes! Kofanger Installeret",
		failed = "Kofangerinstallation mislykkedes!",
		menuheader = " Kofanger og Kofangerkosmetik", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
		menugrille = "Kofangergrill",
		menuFBumper = "Forreste Kofanger",
		menuBBumper = "Bageste Kofanger",
	},
	["exhaust"] = { -- exhaust.lua
		stockMod = "Standard Udstødning..",
		already = " allerede installeret", -- f.eks. "Standard Kofanger allerede Installeret"
		installed = "Succes! Udstødning Installeret",
		failed = "Udstødninginstallation mislykkedes!",
		menuheader = " Udstødningsmodifikation", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
	},
	["exterior"] = { -- exterior.lua
		stockMod = "Standard Udvendig Modifikation..",
		installed = "Succes! Udvendig Modifikation Installeret",
		failed = "Udvendig Modifikation installation mislykkedes!",
		menuheader = " Udvendig Modifikation", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
		label1 = "Pynt A",
		label2 = "Pynt B",
		label3 = "Bagagerum",
		label4 = "Motorkasse",
		label5 = "Filter",
		label6 = "Støddæmpere",
		label7 = "Hydraulik",
		label8 = "Hjulkasser",
		label9 = "Brændstoftanke",
		label10 = "Antenner",
	},
	["hood"] = { -- hood.lua
		stockMod = "Standard Motorhjelm..",
		installed = "Succes! Motorhjelm Installeret",
		failed = "Motorhjelminstallation mislykkedes!",
		menuheader = " Motorhjelmsmodifikation", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
	},
	["horns"] = { -- horns.lua
		installed = "Succes! Horn Installeret",
		failed = "Horninstallation mislykkedes!",
		menuheader = " Hornmodifikation", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
	},
	["interior"] = { -- interior.lua
		stockMod = "Standard Interiørmodifikation..",
		installed = "Succes! Interiørmodifikation Installeret",
		failed = "Interiørmodifikationinstallation mislykkedes!",
		menuheader = " Interiørmodifikation", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
		label1 = "Rullebur",
		label2 = "Ornamenter",
		label3 = "Instrumentbræt",
		label4 = "Instrumenter",
		label5 = "Dørhøjttalere",
		label6 = "Rat",
		label7 = "Gearskiftehåndtag",
		label8 = "Plaques",
		label9 = "Højttalere",
	},
	["livery"] = { -- exhaust.lua
		oldMod = "gammel",
		already = " allerede installeret", -- f.eks. "Standard Kofanger allerede Installeret"
		installed = "Succes! Liveri Installeret",
		failed = "Liveriinstallation mislykkedes!",
		menuheader = " Liverimodifikation", -- f.eks. "Sultan RS Kofanger og Kofangerkosmetik"
	},
	["nos"] = { -- exhaust.lua
		notinstalled = "Turbo er ikke installeret",
		installing = "Succes! Installerer NOS",
		installed = "Succes! NOS Installeret",
		failed = "NOS-installation mislykkedes!",
		removing = "Fjerner NOS-beholder",
		removed = "NOS-beholder fjernet",
		remfail = "Mislykkedes i at fjerne NOS-beholder",
		nosColour = "NOS Tømningsfarve",
		boostmode = "Boost-tilstand",
		purgemode = "Tømnings-tilstand",
		boost = "Boost-kraft: ",
		spray = "Spray-styrke: ",
	},
	["paint"] = { -- paints.lua
		primary = "Primær",
		secondary = "Sekundær",
		pearl = "Perlemor",
		wheel = "Hjul",
		dashboard = "Instrumentbræt",
		interior = "Interiør",
		classic = "Klassisk",
		metallic = "Metallic",
		matte = "Mat",
		metals = "Metaller",
		chameleon = "Chameleon",
		installing = "Succes! Installerer Maling",
		installed = "Succes! Maling Installeret",
		failed = "Malinginstallation mislykkedes!",
		menuheader = " Omlakering",
	},
	["paintrgb"] = {
		select = "Valg:",
		finish = "Afslut Valg:",
		error = "Hex-kode skal være 6 tegn",
		customheader = "Brugerdefineret HEX og RGB",
		chrome = "Krom",
		hex = "HEX Vælger",
		rgb = "RGB Vælger",
	},
	["plates"] = { --paints.lua
		already = "Nummerplade Allerede Installeret!",
		installing = "Installerer Nummerplader..",
		installed = "Succes! Nummerplader Installeret",
		failed = "Nummerpladsinstallation mislykkedes!",
		menuheader = " Nummerpladeændring",
		label1 = "Nummerpladeholder",
		label2 = "Smykkenummerplader",
		label3 = "Tilpassede nummerplader",
		menuheader2 = " Tilpassede nummerpladestilarter",
	},
	["rims"] = {
		installing = "Installerer Fælge..",
		installed = "Succes! Fælge Installeret",
		failed = "Fælgeinstallation mislykkedes!",
		menuheader = "Fælgemodifikation",
		label1 = "Sport",
		label2 = "Muscle",
		label3 = "Lowrider",
		label4 = "SUV",
		label5 = "Offroad",
		label6 = "Tuner",
		label7 = "Highend",
		label8 = "Benny's Originale",
		label9 = "Benny's Skræddersyede",
		label10 = "Åbenhjulet",
		label11 = "Gade",
		label12 = "Bane",
		label13 = "Forhjul",
		label14 = "Baghjul",
		label15 = "Motorcykel",
		labelcustom = "Tilpassede Fælge",
	},
	["rollcage"] = { --rollcage.lua
		installed = "Succes! Rullebur Installeret",
		failed = "Rulleburinstallation mislykkedes!",
		menuheader = " Rulleburmodifikation",
	},
	["roof"] = { --roof.lua
		installed = "Succes! Tag Installeret",
		failed = "Taginstallation mislykkedes!",
		menuheader = " Tagmodifikation",
	},
	["seat"] = { --seat.lua
		installed = "Succes! Sæde Installeret",
		failed = "Sædeinstallation mislykkedes!",
		menuheader = " Sædændring",
	},
	["skirts"] = { --skirts.lua
		installed = "Succes! Skørter Installeret",
		failed = "Skørteinstallation mislykkedes!",
		menuheader = " Skørter og Skærmkosmetik",
		menuskirt = "Skørter",
		menuRF = "Højre Skærm",
		menuLF = "Venstre Skærm",
	},
	["spoilers"] = { --spoilers.lua
		installed = "Succes! Spoiler Installeret",
		failed = "Spoilerinstallation mislykkedes!",
		menuheader = " Spoilermodifikation",
	},
	["smoke"] = { --tiresmoke.lua
		already = "Denne farve er allerede anvendt!",
		installing = "Installerer Dækryg..",
		installed = "Succes! Røg Installeret",
		failed = "Røginstallation mislykkedes!",
		menuheader = " Dækrygændring",
		remove = "Fjern Røg",
		custom = "TILPAS RBG",
		black = "Sort",
		white = "Hvid",
		blue = "Blå",
		eblue = "Elektrisk Blå",
		mgreen = "Myntegrøn",
		lgreen = "Limegrøn",
		yellow = "Gul",
		gshower = "Guldsprøjt",
		orange = "Orange",
		red = "Rød",
		ppink = "Pony Pink",
		hpink = "Hot Pink",
		purple = "Lilla",
		blacklight = "Blacklight",
		submit = "Send",
	},
	["windows"] = { --windows.lua
		installed = "Succes! Tonet Ruder Installeret",
		failed = "Tonet Rudeinstallation mislykkedes!",
		menuheader = " Tonede Ruder",
		label1 = "Fjern Toning",
		label2 = "Limo",
		label3 = "Grøn",
		label4 = "Lys Toning",
		label5 = "Mørk Toning",
		label6 = "Ren Sort",
	},
	["stores"] = {
		browse = "Gennemse Butik",
		tools = "Mekanikerværktøj",
		perform = "Ydelsesgenstande",
		cosmetic = "Kosmetiske genstande",
	},
	["crafting"] = { --crafting.lua
		menuheader = "Mekanikerhåndværk",
		toolheader = "Mekanikerværktøj",
		performheader = "Ydelsesgenstande",
		cosmetheader = "Kosmetiske genstande",
		numitems = " genstande", -- til menuen. f.eks. "11 genstande"
		ingredients = "Du har ikke de korrekte ingredienser",
	},
	["payments"] = { --payments.lua
		charge = "Opkræv kunden",
	},
	["check"] = { --check_tunes.lua
		plate = "Nummerplade: [",
		value = "]<br>Pris: $",
		unavail = "❌ Utilgængelig",
		notinstall = "Ikke installeret",
		reinforced = "Forstærket karrosseri",
		xenoninst = "Xenon installeret",
		tireinst = "Installeret",

		label1 = "Motorer:",
		label2 = "Bremser:",
		label3 = "Affjedring:",
		label4 = "Transmission:",
		label5 = "Panser:",
		label6 = "Turbo:",
		label7 = "Xenon:",
		label8 = "Drift Dæk:",
		label9 = "Kuglesikre Dæk:",
		label10 = "Liste over mulige kosmetik",
		label11 = "Køretøj: ",

		label12 = " muligheder ]",
		label13 = "- Ekstern kosmetik -",
		label14 = "- Intern kosmetik -",
		label15 = "Spoilere - [",
		label16 = "Forbumpere - [",
		label17 = "Bagbumpere - [",
		label18 = "Siderør - [",
		label19 = "Udstødninger - [",
		label20 = "Griller - [",
		label21 = "Motorhjælme - [",
		label22 = "Venstre forskærm - [",
		label23 = "Højre forskærm - [",
		label24 = "Tag - [",
		label25 = "Nummerpladeholdere - [",
		label26 = "Pynteplader - [",
		label27 = "Trim A - [",
		label28 = "Trim B - [",
		label29 = "Bagagerum - [",
		label30 = "Motorblokke - [",
		label31 = "Luftfiltre - [",
		label32 = "Motorstrut - [",
		label33 = "Skærmkapper - [",

		label34 = "Rullebure - [",
		label35 = "Pyntegenstande - [",
		label36 = "Instrumentborde - [",
		label37 = "Måleinstrumenter - [",
		label38 = "Dørhøjttalere - [",
		label39 = "Sæder - [",
		label40 = "Rat - [",
		label41 = "Gearskiftere - [",
		label42 = "Plaques - [",
		label43 = "Højttalere - [",
		label44 = "Hydraulik - [",
		label45 = "Antenner - [",
		label46 = "Brændstoftanke - [",
		label47 = "Ja",
		label48 = "Nej",
		label49 = "Vil du fjerne bremsene?",
		label50 = "Vil du fjerne motoren?",
		label51 = "Vil du fjerne affjedringen?",
		label52 = "Vil du fjerne transmissionen?",
		label53 = "Vil du fjerne rustningen?",
		label54 = "Vil du fjerne turboen?",
		label55 = "Vil du fjerne xenon-lygterne?",
		label56 = "Vil du fjerne dæk?",
		label57 = "Vil du tømme lattergasbeholderen?",
		label58 = "Lattergas:",
	},
	["repair"] = {
		browse = "Gennemse Lager",
		materials = "Du har ikke nok materialer",
		checkeng = "Tjekker motorskader..",
		checkbody = "Tjekker karrosseriskader..",

		engine = "Motor",
		body = "Karrosseri",
		radiator = "Oliespejl",
		driveshaft = "Akselskaft",
		brakes = "Tændrør",
		clutch = "Bilbatteri",
		tank = "Brændstoftank",
		replacetire = "Udskift Dæk",
		tire = "Hjul",

		repairing = "Reparerer ",
		changing = "Udskifter ",
		repaired = " fuldt reparere",
		cancel = " Reparation annulleret!",
		nomaterials = "Der er ikke nok materialer i kassen",
		failinfo = "Kunne ikke hente oplysninger om bilen, prøv at bruge værktøjerne igen",

		cost = "<br>Pris: ",
		status = "Status: ",
		doyou = "Vil du reparere ",

		applyduct = "Anvender gaffatape..",
		ductfull = "Du kan ikke bruge mere gaffatape på denne bil",
		nocar = "Der er ingen køretøjer i nærheden",
	},
	["police"] = {
		userepair = "Brug reparationsstation",
		repair = "Reparation",
		extras = "Ekstraudstyr",
		plates = "Nummerplader",
		livery = "Beklædning",
		spoiler = "Spoilere",
		cleaning = "Rengører køretøj...",
		engine = "Reparerer motor...",
		body = "Reparerer karrosseri...",
		complete = "Reparation fuldført",
	},
	["manual"] = {
		tyres = "Udskifter beskadigede dæk",
		window = "Fjerner beskadigede vinduer",
		doors = "Reparerer døre",
	},
	["carwax"] = {
		head1 = "Rengør køretøj",
		head2 = "Rengør og voks",
		head3 = "Rengør og premium voks",
		head4 = "Rengør og ultimativ voks",
	},
	["extras"] = {
		clean = "Køretøj rengjort",
		doorerr = "Dørfejl",
		locked = "Køretøjets døre er låst",
		flipping = "Køretøj vendes...",
		flipped = "Succes! Køretøj vendt",
		failed = "Køretøjsvending mislykkedes!",
		noseat = "Intet sædenummer indtastet",
		moveseat = "Du flytter til sæde ",
		fastseat = "Dette køretøj kører for hurtigt..",
		notseat = "Dette sæde er ikke tilgængeligt..",
		harness = "Du har et racerseler på, du kan ikke skifte sæde..",
	},
	["functions"] = {
		distance = "Afstand: ",
		inCar = "Kan ikke gøre dette inde fra køretøjet",
		outCar = "Kan ikke gøre dette uden for køretøjet",
		locked = "Køretøjet er låst",
		nearby = "Der er ingen køretøj i nærheden",
		shop = "Kan ikke arbejde uden for en butik",
		mechanic = "Kun en mekaniker ved, hvordan man gør dette",
	},
	["servfunction"] = {
		checkdamage = "Tjek køretøjet for skader",
		checkmods = "Tjek tilgængelige ændringer på et køretøj",
		flipvehicle = "Vend nærmeste køretøj",
		togglesound = "Aktiver opgraderede lydmotorlyde",
		togglesoundesc = "Indstil opgraderede motorlyde TIL eller FRA",
		cleancar = "Rengør bilen",
		hood = "Åbn/luk motorhjelmen",
		trunk = "Åbn/luk bagagerummet",
		door = "Åbn/luk dør [0-3]",
		seat = "Flyt til en anden sæde [-1 til 10]",
	},
	["previews"] = {
		changes = "Antal ændringer: ",
	},
	["garage"] = {
		jobgarage = "Jobgarage",
		vehout = "Køretøj uden for garagen",
		remveh = "Fjern køretøj",
		cantspawn = " i vejen",
		marker = "Jobkøretøj markeret på kortet",
		markername = "Jobkøretøj",
	},
	--Below are names of items/mods that can't be reteived natively
	vehiclePlateOptions = {
		{ name = "Blå på hvid #1", id = 0 },
		{ name = "Blå på hvid #2", id = 3 },
		{ name = "Blå på hvid #3", id = 4 },
		{ name = "Gul på blå", id = 2 },
		{ name = "Gul på sort", id = 1 },
		{ name = "North Yankton", id = 5 },
	},
	vehicleNeonOptions = {
		{ name = "Hvid", R = 255, G = 255, B = 255 },
        { name = "Blå", R = 2, G = 21, B = 255 },
        { name = "Elektrisk blå", R = 3, G = 83, B = 255 },
        { name = "Mint grøn", R = 0, G = 255, B = 140 },
        { name = "Lime grøn", R = 94, G = 255, B = 1 },
        { name = "Gul", R = 255, G = 255, B = 0 },
        { name = "Golden Shower", R = 255, G = 150, B = 0 },
        { name = "Orange", R = 255, G = 62, B = 0 },
        { name = "Rød", R = 255, G = 1, B = 1 },
        { name = "Pony Pink", R = 255, G = 50, B = 100 },
        { name = "Hot Pink", R = 255, G = 5, B = 190 },
        { name = "Lilla", R = 35, G = 1, B = 255 },
        { name = "Sortlys", R = 15, G = 3, B = 255 }
	},
	vehicleHorns = {
		{ name = "lastbil Horn", id = 0 },
		{ name = "Politi Horn", id = 1 },
		{ name = "Klovne Horn", id = 2 },
		{ name = "Musik Horn 1", id = 3 },
		{ name = "Musik Horn 2", id = 4 },
		{ name = "Musik Horn 3", id = 5 },
		{ name = "Musik Horn 4", id = 6 },
		{ name = "Musik Horn 5", id = 7 },
		{ name = "Sørgelig Trombone", id = 8 },
		{ name = "KLassisk Horn 1", id = 9 },
		{ name = "KLassisk Horn 2", id = 10 },
		{ name = "KLassisk Horn 3", id = 11 },
		{ name = "KLassisk Horn 4", id = 12 },
		{ name = "KLassisk Horn 5", id = 13 },
		{ name = "KLassisk Horn 6", id = 14 },
		{ name = "KLassisk Horn 7", id = 15 },
		{ name = "Skala - Do", id = 16 },
		{ name = "Skala - Re", id = 17 },
		{ name = "Skala - Mi", id = 18 },
		{ name = "Skala - Fa", id = 19 },
		{ name = "Skala - Sol", id = 20 },
		{ name = "Skala - La", id = 21 },
		{ name = "Skala - Ti", id = 22 },
		{ name = "Skala - Do", id = 23 },
		{ name = "Jazz Horn 1", id = 24 },
		{ name = "Jazz Horn 2", id = 25 },
		{ name = "Jazz Horn 3", id = 26 },
		{ name = "Jazz Horn Loop", id = 27 },
		{ name = "Star Spangled Banner 1", id = 28 },
		{ name = "Star Spangled Banner 2", id = 29 },
		{ name = "Star Spangled Banner 3", id = 30 },
		{ name = "Star Spangled Banner 4", id = 31 },
		{ name = "Klassisk Horn 8 Loop", id = 32 },
		{ name = "Klassisk Horn 9 Loop", id = 33 },
		{ name = "Klassisk Horn 10 Loop", id = 34 },
		{ name = "Klassisk Horn 8", id = 35 },
		{ name = "Klassisk Horn 9", id = 36 },
		{ name = "Klassisk Horn 10", id = 37 },
		{ name = "Begravelses Loop", id = 38 },
		{ name = "Begravelse", id = 39 },
		{ name = "Spooky Loop", id = 40 },
		{ name = "Spooky", id = 41 },
		{ name = "San Andreas Loop", id = 42 },
		{ name = "San Andreas", id = 43 },
		{ name = "Liberty City Loop", id = 44 },
		{ name = "Liberty City", id = 45 },
		{ name = "Festlig 1 Loop", id = 46 },
		{ name = "Festlig 1", id = 47 },
		{ name = "Festlig 2 Loop", id = 48 },
		{ name = "Festlig 2", id = 49 },
		{ name = "Festlig 3 Loop", id = 50 },
		{ name = "Festlig 3", id = 51 },
		{ name = "Luft Horn 1 Loop", id = 52},
		{ name = "Luft Horn 1", id = 53},
		{ name = "Luft Horn 2 Loop", id = 54},
		{ name = "Luft Horn 2", id = 55},
		{ name = "Luft Horn 3 Loop", id = 56},
		{ name = "Luft Horn 3", id = 57},
	},
	vehicleResprayOptionsClassic = {
		{ name = "Sort", id = 0 },
		{ name = "Kulsort", id = 147 },
		{ name = "Grafitsort", id = 1 },
		{ name = "Antracit sort", id = 11 },
		{ name = "Sort stål", id = 2 },
		{ name = "Mørk stål", id = 3 },
		{ name = "Sølv", id = 4 },
		{ name = "Blålig sølv", id = 5 },
		{ name = "Rullet stål", id = 6 },
		{ name = "Skygge sølv", id = 7 },
		{ name = "Sten sølv", id = 8 },
		{ name = "Midnatssølv", id = 9 },
		{ name = "Støbejern sølv", id = 10 },
		{ name = "Rød", id = 27 },
		{ name = "Torino rød", id = 28 },
		{ name = "Formel rød", id = 29 },
		{ name = "Lavarød", id = 150 },
		{ name = "Blaze rød", id = 30 },
		{ name = "Grace rød", id = 31 },
		{ name = "Granat rød", id = 32 },
		{ name = "Solnedgangsrød", id = 33 },
		{ name = "Cabernet rød", id = 34 },
		{ name = "Vinrød", id = 143 },
		{ name = "Slikrød", id = 35 },
		{ name = "Hot pink", id = 135 },
		{ name = "Pfsiter pink", id = 137 },
		{ name = "Laksrosa", id = 136 },
		{ name = "Solopgang orange", id = 36 },
		{ name = "Orange", id = 38 },
		{ name = "Lys orange", id = 138 },
		{ name = "Guld", id = 99 },
		{ name = "Bronze", id = 90 },
		{ name = "Gul", id = 88 },
		{ name = "Racegul", id = 89 },
		{ name = "Duggul", id = 91 },
		{ name = "Mørkegrøn", id = 49 },
		{ name = "Racergrøn", id = 50 },
		{ name = "Havgrøn", id = 51 },
		{ name = "Olivengrøn", id = 52 },
		{ name = "Lysegrøn", id = 53 },
		{ name = "Benzingrøn", id = 54 },
		{ name = "Limegrøn", id = 92 },
		{ name = "Midnatblå", id = 141 },
		{ name = "Galaxyblå", id = 61 },
		{ name = "Mørkeblå", id = 62 },
		{ name = "Saxonblå", id = 63 },
		{ name = "Blå", id = 64 },
		{ name = "Marineblå", id = 65 },
		{ name = "Havneblå", id = 66 },
		{ name = "Diamantblå", id = 67 },
		{ name = "Surfblå", id = 68 },
		{ name = "Søblå", id = 69 },
		{ name = "Racerblå", id = 73 },
		{ name = "Ultra blå", id = 70 },
		{ name = "Lyseblå", id = 74 },
  	},
	vehicleResprayOptionsMatte = {
		{ name = "Sort", id = 12 },
		{ name = "Grå", id = 13 },
		{ name = "Lysegrå", id = 14 },
		{ name = "Is-hvid", id = 131 },
		{ name = "Blå", id = 83 },
		{ name = "Mørkeblå", id = 82 },
		{ name = "Midnatsblå", id = 84 },
		{ name = "Midnatslilla", id = 149 },
		{ name = "Schafter lilla", id = 148 },
		{ name = "Rød", id = 39 },
		{ name = "Mørkerød", id = 40 },
		{ name = "Orange", id = 41 },
		{ name = "Gul", id = 42 },
		{ name = "Limegrøn", id = 55 },
		{ name = "Grøn", id = 128 },
		{ name = "Skovgrøn", id = 151 },
		{ name = "Bladgrøn", id = 155 },
		{ name = "Olivenbrun", id = 152 },
		{ name = "Mørkebrun", id = 153 },
		{ name = "Ørkensand", id = 154 },
	},

	vehicleResprayOptionsMetals = {
		{ name = "Børstet stål", id = 117 },
		{ name = "Børstet sort stål", id = 118 },
		{ name = "Børstet aluminium", id = 119 },
		{ name = "Rent guld", id = 158 },
		{ name = "Børstet guld", id = 159 },
		{ name = "Krom", id = 120 },
	},

	vehicleResprayOptionsChameleon = {
		{ name = "Monokrom", id = 223 },
		{ name = "Kromatisk aberration", id = 236 },
		{ name = "Nat & Dag", id = 224 },
		{ name = "The Verlierer", id = 225 },
		{ name = "Sprunk Extreme", id = 226 },
		{ name = "Vice City", id = 227 },
		{ name = "Solnedgang", id = 233 },
		{ name = "Temperatur", id = 238 },
		{ name = "Synthwave Nights", id = 228 },
		{ name = "Fire årstider", id = 229 },
		{ name = "The Seven", id = 234 },
		{ name = "Maisonette 9 Throwback", id = 230 },
		{ name = "Bubblegum", id = 231 },
		{ name = "Fuld regnbue", id = 232 },
		{ name = "Kamen Rider", id = 235 },
		{ name = "Det er jul", id = 237 },
	},
}
