Loc["de"] = {
	["common"] = { --commonly used strings
		owned = "Fahrzeug gehört keinem und kann nicht modifiziert werden",
		close = "Schließen",
		ret = "Zurück",
		stock = "Standart", -- Default, Original, whatever word you use for this
		current = "Zurzeit installiert",
		noOptions = "Keine Optionen für dieses Item",
		notinstall = "Nicht Installiert",
		installing = "Installiert ",
		installed = "Eingebaut!",
		instfail = " Einbau Fehlgeschlagen!",
		removed = "Entfernt!",
		removing = "Entferne ",
		remfail = " Entfernen fehlgeschlagen!",
		cant = "Kann in dieses Fahrzeug nicht eingebaut werden",
		amountoption = "Anzahl an Optionen: ",
		already = " bereits installiert", -- eg. "Stock Bumper already Installed"
		menuinstalled = " Optionen] installiert: ", --eg "[4 Options] Installed: Grille 1"
		nearwheel = "Du musst näher am Reifen sein",
		nearengine = "Du musst näher am Reifen sein",
		closer = "Gehe näher an die Scheinwerfer",
		harness = "Lege Renngurte an..",
	},
	["tires"] = {
		swap = "Schussfeste Reifen entfernt",
		swap2 = "Driftreifen entfernen fehlgeschlagen",
	},
	["xenons"] = {
		notinstall = "Xenonlichter nicht installiert",
		--Menus
		neonheader1 = "Beleuchtungssteuerung",
		neonheader2 = "Unterbodenbeleuchtungsteuerung",
		neonheader3 = "Unterbodenbeleuchtungsteuerung",
		neonheader4 = "Xenonlichtersteuerung",
		customheader = "Individuelles RBG",
		customconfirm = "ANWENDEN",
		neontxt1 = "Feinsteuerung der Neonbeleuchtung",
		toggle = "ALLE AKTIVIEREN",
		front = "Vorne",
		right = "Rechts",
		left = "Links",
		back = "Hinten",
		neontxt2 = "Unterbodenbeleuchtungsfarbe ändern",
		xenonheader = "Xenonsteuerung",
		xenontxt = "Scheinwerferfarbe anpassen",
	},
	--Cosmetic Items
	["bumpers"] = {
		menugrille = "Kühlergrill",
		menuFBumper = "Vordere Stoßstangen",
		menuBBumper = "Hintere Stoßstangen",
	},
	["exhaust"] = {
		menuheader = " Auspuff",
	},
	["exterior"] = {
		stockMod = "Standart Exterior",

		label1 = "Trim A",
		label2 = "Trim B",
		label3 = "Kofferraum",
		label4 = "Motor Block",
		label5 = "Filter",
		label6 = "Streben",
		label7 = "Hydraulik",
		label8 = "Arch Covers",
		label9 = "Kraftstofftank",
		label10 = "Aerials",
	},
	["hood"] = {
		menuheader = " Motorhauben",
	},
	["horns"] = {
		menuheader = " Hupen",
	},
	["interior"] = {
		label1 = "Überrollkäfig",
		label2 = "Ornaments",
		label3 = "Armaturenbrett",
		label4 = "Dials",
		label5 = "Türlautsprecher",
		label6 = "Lenkrad",
		label7 = "Schalthebel",
		label8 = "Plaketten",
		label9 = "Lautsprecher",
	},
	["livery"] = {
		oldMod = "old",
		menuheader = " Aufkleber",
		menuoldheader = " Dach Aufkleber",
	},
	["nos"] = {
		notinstalled = "Turbo ist nicht installiert",

		nosColour = "NOS Purge Farbe",
		boostmode = "Boost Mode",
		purgemode = "Purge Mode",
		boost = "Boost Power: ",
		spray = "Spray Stärke: ",
	},
	["paint"] = { --paints.lua
		primary = "Primär",
		secondary = "Sekundär",
		pearl = "Perleffekt",
		wheel = "Felgen",
		dashboard = "Armaturenbrett",
		interior = "Innenraum",

		classic = "Klassisch",
		metallic = "Metallisch",
		matte = "Matt",
		metals = "Metall",
		chameleon = "Chameleon",

		menuheader = " Lackierung",
	},
	["paintrgb"] = {
		select = "Auswahl:",
		finish = "Fertig:",
		error = "Die Eingabe des Hex-Codes muss 6 Zeichen umfassen.",
		customheader = "Individueller HEX",
		chrome = "Chrom",
		hexP = "HEX Auswahl",
		rgbP = "RGB Auswahl",
	},
	["plates"] = {
		label1 = "Kennzeichenhalter",
		label2 = "Vanity Kennzeichen",
		label3 = "Custom Kennzeichen",
	},
	["rims"] = {
		menuheader = "Felgen Modifikation",

		label1 = "Sport",
		label2 = "Muscle",
		label3 = "Lowrider",
		label4 = "SUV",
		label5 = "Offroad",
		label6 = "Tuner",
		label7 = "Highend",
		label8 = "Benny's Originals",
		label9 = "Benny's Bespoke",
		label10 = "Open Wheel",
		label11 = "Street",
		label12 = "Track",
		label13 = "Front Wheel",
		label14 = "Back Wheel",
		label15 = "Motorcycle",

		labelcustom = "Custom Felgen",
	},
	["rollcage"] = {
		menuheader = " Überrollkäfig",
	},
	["roof"] = {
		menuheader = " Dach",
	},
	["seat"] = {
		menuheader = " Sitze", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["skirts"] = {
		menuskirt = "Schweller",
		menuRF = "Rechte Kotflügel",
		menuLF = "Linke Kotflügel",
	},
	["spoilers"] = {
		menuheader = " Spoiler", --eg "Sultan RS Grille and Bumper Cosmetics"
	},
	["smoke"] = {
		already = "Diese Farbe wird derzeit verwendet",
		menuheader = " Reifenqualm", --eg "Sultan RS Grille and Bumper Cosmetics"

		remove = "Rauch entfernen",
		custom = "CUSTOM RBG",
		black = "Schwarz",
		white = "Weiß",
		blue = "Blau",
		eblue = "Elektrisches Blau",
		mgreen = "Minz Grün",
		lgreen = "Lime Grün",
		yellow = "Gelb",
		gshower = "Goldene Dusche",
		orange = "Orange",
		Red = "Rot",
		ppink = "Pony Pink",
		hpink = "Hot Pink",
		purple = "Lila",
		blacklight = "Schwarzlicht",
	},
	["windows"] = {
		menuheader = " Fenster Farbton",
	},
	["stores"] = {
		browse = "Shop Öffnen",
		tools = "Mechaniker Werkzeuge",
		perform = "Performance Gegenstände",
		cosmetic = "Kosmetik Gegenstände",
		repairs = "Reparatur Gegenstände",
		nos = "NOS Gegenstände",
	},
	["crafting"] = { --crafting.lua
		menuheader = "Mechaniker Herstellung",
		toolheader = "Mechaniker Werkzeuge",
		repairheader = "Reparatur Gegenstände",
		performheader = "Performance Gegenstände",
		cosmetheader = "Kosmetik Gegenstände",
		nosheader = "NOS Gegenstände",
		numitems = " Gegenstände", --for menu. eg. "11 items"
	},
	["payments"] = { --payments.lua
		charge = "Rechnung erstellen",
	},
	["check"] = { --check_tunes.lua
		plate = "Kennzeichen: [",
		value = "]<br>Wert: $",
		unavail = "❌ Nicht verfügbar",

		label1 = "Motor:",
		label2 = "Bremsen:",
		label3 = "Federung:",
		label4 = "Getriebe:",
		label5 = "Armor:",
		label6 = "Turbo:",
		label7 = "Xenon:",
		label8 = "Drift Reifen:",
		label9 = "Bulletproof Reifen:",
		label10 = "Liste möglicher Kosmetik",
		label11 = "Fahrzeug: ",

		label12 = " Optionen ]",
		label13 = "- External Kosmetik -",
		label14 = "- Internal Kosmetik - ",
		label15 = "Spoilers - [ ",
		label16 = "Vordere Stoßstangen - [ ",
		label17 = "Hintere Stoßstangen - [ ",
		label18 = "Seitenschweller - [ ",
		label19 = "Auspuff - [ ",
		label20 = "Kühlergrille - [ ",
		label21 = "Haube - [ ",
		label22 = "Linker Kotflügel - [ ",
		label23 = "Rechter Kotflügel - [ ",
		label24 = "Dach - [ ",
		label25 = "Kennzeichenhalten - [ ",
		label26 = "Vanity Kennzeichen - [ ",
		label27 = "Trim A - [ ",
		label28 = "Trim B - [ ",
		label29 = "Kofferraum - [ ",
		label30 = "Motorblock - [ ",
		label31 = "Luft Filter - [ ",
		label32 = "Motor - [ ",
		label33 = "Arch Covers - [ ",

		label34 = "Überrollkäfige - [ ",
		label35 = "Ornamente - [ ",
		label36 = "Dashboards - [ ",
		label37 = "Dials - [ ",
		label38 = "Türlautsprecher - [ ",
		label39 = "Sitze - [ ",
		label40 = "Lenkrad - [ ",
		label41 = "Shifter Leavers - [ ",
		label42 = "Plaques - [ ",
		label43 = "Lautsprecher - [ ",
		label44 = "Hydraulics - [ ",
		label45 = "Aerials - [ ",
		label46 = "Tank - [ ",
		label47 = "Ja",
		label48 = "Nein",
		label57 = "Willst du das Nitro ablassen?",
		label50 = "Antilag:",
		label51 = "Renngurt:",
		label58 = "Nitro:",
	},
	["repair"] = {
		browse = "Lager öffnen",
		materials = "Du hast nicht genug Materialien",
		checkeng = "Motorschaden überprüfen",
		checkbody = "Karosserieschaden überprüfen",

		engine = "Motor",
		body = "Karosserie",
		oil = "Kühler",
		driveshaft = "Antriebswelle",
		spark = "Bremsen",
		battery = "Kupplung",
		tank = "Tank",
		replacetire = "Ersetze Reifen",
		tire = "Reifen",

		repairing = "Repariere ",
		changing = "Wechsle ",
		repaired = " komplett repariert",
		cancel = " Reparatur abgebrochen",
		nomaterials = "Es gibt nicht genug Materialien im Lager",

		cost = "<br>Kosten: ",
		status = "Status: ",
		doyou = "Willst du das reparieren: ",

		applyduct = "Klebeband anbringen",
		ductfull = "Sie können an diesem Auto kein Klebeband mehr verwenden",
		nocar = "Es ist kein Fahrzeug in der nähe",
	},
	["police"] = {
		header = "Modifikations Station",
		userepair = "Verwenden Sie die Reparaturstation",
		repaired = "Reparatur",
		extras = "Extras",
		plates = "Kennzeichen",
		livery = "Aufkleber",
		spoiler = "Spoiler",
		cleaning = "Säubere Fahrzeug...",
		engine = "Repariere Motor...",
		body = "Repariere Karosserie...",
		complete = "Reparatur abgeschlossen",
	},
	["manual"] = {
		tyres = "Ersetze defekte Reifen",
		window = "Ersetze defekte Scheiben",
		doors = "Repariere Türen",
	},
	["carwax"] = {
		head1 = "Fahrzeug säubern",
		head2 = "Fahrzeug säubern + Wachs",
		head3 = "Fahrzeug säubern Premium Wachs",
		head4 = "Fahrzeug säubern und Ultimate Wachs",
	},
	["extras"] = {
		clean = "Fahrzeug Sauber",
		doorerr = "Tür fehler",
		locked = "Fahrzeugtüren geschlossen",
		flipping = "Fahrzeug umdrehen",
		flipped = "Fahrzeug Erfolgreich umgedreht",
		failed = "Fahrzeug umdrehen fehlgeschlagen",
		noseat = "Keine Platznummer eingegeben",
		moveseat = "Du setzt dich auf Sitz ",
		fastseat = "Dieses Fahrzeug fährt zu schnell",
		notseat = "Dieser Platz ist nicht verfügbar",
		harness = "Sie haben ein Renngurt an, du kannst den Sitz nicht wechseln",
	},
	["functions"] = {
		distance = "Distanz: ",
		inCar = "Aus dem Fahrzeuginneren ist dies nicht möglich",
		outCar = "Von außerhalb des Fahrzeugs ist dies nicht möglich",
		locked = "Fahrzeug verschlossen",
		nearby = "Es ist kein Fahrzeug in der nähe",
		shop = "Kann nicht außerhalb vom Mechaniker arbeiten",
		mechanic = "Nur ein Mechaniker weiß, wie das geht",
		checking = "Überprüfe Lager.."
	},
	["servfunction"] = {
		checkdamage = "Fahrzeug auf Schäden prüfen",
		checkmods = "Überprüfen Sie die für ein Fahrzeug verfügbaren Mods",
		flipvehicle = "Drehen Sie das Fahrzeug um",
		togglesound = "Aktiviere Verbesserten Motorsounds",
		togglesoundesc = "Verbesserte Motorgeräusche ein- oder ausschalten",
		cleancar = "Auto säubern",
		hood = "Öffne/Schließe Haube",
		trunk = "Öffne/Schließe Kofferraum",
		door = "Öffne/Schließe Tür [0-3]",
		seat = "Wechsle den Sitz [-1 to 10]",
	},
	["previews"] = {
		changes = "Anzahl Veränderungen: ",
	},
	--Below are names of items/mods that can't be reteived natively
	vehicleWindowOptions = {
		{ name = "Limo", id = 4 },
		{ name = "Grün", id = 5 },
		{ name = "Leichter Rauch", id = 3 },
		{ name = "Dunkler Rauch", id = 2 },
		{ name = "Tief Schwarz", id = 1 }
	},
	vehiclePlateOptions = {
		{ name = "Blau auf Weiß #2", id = 3 },
		{ name = "Blau auf Weiß #3", id = 4 },
		{ name = "Gelb auf Blau", id = 2 },
		{ name = "Gelb auf Schwarz", id = 1 },
		{ name = "North Yankton", id = 5 },
	},
	vehicleNeonOptions = {
		{ name = "Weiß", R = 255, G = 255, B = 255 },
        { name = "Blau", R = 2, G = 21, B = 255 },
        { name = "Electrischs Blau", R = 3, G = 83, B = 255 },
        { name = "Minz Grün", R = 0, G = 255, B = 140 },
        { name = "Limetten Grün", R = 94, G = 255, B = 1 },
        { name = "Gelb", R = 255, G = 255, B = 0 },
        { name = "Goldene Dusche", R = 255, G = 150, B = 0 },
        { name = "Orange", R = 255, G = 62, B = 0 },
        { name = "Rot", R = 255, G = 1, B = 1 },
        { name = "Pony Pink", R = 255, G = 50, B = 100 },
        { name = "Hot Pink", R = 255, G = 5, B = 190 },
        { name = "Lila", R = 35, G = 1, B = 255 },
        { name = "Schwarzlicht", R = 15, G = 3, B = 255 }
	},
	vehicleHorns = {
		{ name = "LKW Hupe", id = 0 },
		{ name = "Polizei Hupe", id = 1 },
		{ name = "Clown Hupe", id = 2 },
		{ name = "Musikalische Hupe 1", id = 3 },
		{ name = "Musikalische Hupe 2", id = 4 },
		{ name = "Musikalische Hupe 3", id = 5 },
		{ name = "Musikalische Hupe 4", id = 6 },
		{ name = "Musikalische Hupe 5", id = 7 },
		{ name = "Sad Trombone", id = 8 },
		{ name = "Klassische Hupe 1", id = 9 },
		{ name = "Klassische Hupe 2", id = 10 },
		{ name = "Klassische Hupe 3", id = 11 },
		{ name = "Klassische Hupe 4", id = 12 },
		{ name = "Klassische Hupe 5", id = 13 },
		{ name = "Klassische Hupe 6", id = 14 },
		{ name = "Klassische Hupe 7", id = 15 },
		{ name = "Tonleiter - Do", id = 16 },
		{ name = "Tonleiter - Re", id = 17 },
		{ name = "Tonleiter - Mi", id = 18 },
		{ name = "Tonleiter - Fa", id = 19 },
		{ name = "Tonleiter - Sol", id = 20 },
		{ name = "Tonleiter - La", id = 21 },
		{ name = "Tonleiter - Ti", id = 22 },
		{ name = "Tonleiter - Do", id = 23 },
		{ name = "Jazz Hupe 1", id = 24 },
		{ name = "Jazz Hupe 2", id = 25 },
		{ name = "Jazz Hupe 3", id = 26 },
		{ name = "Jazz Hupe Loop", id = 27 },
		{ name = "Star Spangled Banner 1", id = 28 },
		{ name = "Star Spangled Banner 2", id = 29 },
		{ name = "Star Spangled Banner 3", id = 30 },
		{ name = "Star Spangled Banner 4", id = 31 },
		{ name = "Klassische Hupe 8 Loop", id = 32 },
		{ name = "Klassische Hupe 9 Loop", id = 33 },
		{ name = "Klassische Hupe 10 Loop", id = 34 },
		{ name = "Klassische Hupe 8", id = 35 },
		{ name = "Klassische Hupe 9", id = 36 },
		{ name = "Klassische Hupe 10", id = 37 },
		{ name = "Beerdigung Loop", id = 38 },
		{ name = "Beerdigung", id = 39 },
		{ name = "Gruselig Loop", id = 40 },
		{ name = "Gruselig", id = 41 },
		{ name = "San Andreas Loop", id = 42 },
		{ name = "San Andreas", id = 43 },
		{ name = "Liberty City Loop", id = 44 },
		{ name = "Liberty City", id = 45 },
		{ name = "Festival 1 Loop", id = 46 },
		{ name = "Festival 1", id = 47 },
		{ name = "Festival 2 Loop", id = 48 },
		{ name = "Festival 2", id = 49 },
		{ name = "Festival 3 Loop", id = 50 },
		{ name = "Festival 3", id = 51 },
		{ name = "Luftdruck Hupe 1 Loop", id = 52},
		{ name = "Luftdruck Hupe 1", id = 53},
		{ name = "Luftdruck Hupe 2 Loop", id = 54},
		{ name = "Luftdruck Hupe 2", id = 55},
		{ name = "Luftdruck Hupe 3 Loop", id = 56},
		{ name = "Luftdruck Hupe 3", id = 57},
	},
	vehicleResprayOptionsClassic = {
		{ name = "Schwarz", id = 0 },
		{ name = "Carbon Schwarz", id = 147 },
		{ name = "Graphit", id = 1 },
		{ name = "Antrazit Schwarz", id = 11 },
		{ name = "Schwarzer Stahll", id = 2 },
		{ name = "Dunkler Stahll", id = 3 },
		{ name = "Silber", id = 4 },
		{ name = "Bluish Silber", id = 5 },
		{ name = "Gerollter Stahl", id = 6 },
		{ name = "Schatten Silber", id = 7 },
		{ name = "Stein Silber", id = 8 },
		{ name = "Mitternacht Silber", id = 9 },
		{ name = "Gegossenes Eisen Silber", id = 10 },
		{ name = "Rot", id = 27 },
		{ name = "Torino Rot", id = 28 },
		{ name = "Formel Rot", id = 29 },
		{ name = "Lava Rot", id = 150 },
		{ name = "Blaze Rot", id = 30 },
		{ name = "Grace Rot", id = 31 },
		{ name = "Garnet Rot", id = 32 },
		{ name = "Sonnenuntergangs Rot", id = 33 },
		{ name = "Cabernet Rot", id = 34 },
		{ name = "Wein Rot", id = 143 },
		{ name = "Candy Rot", id = 35 },
		{ name = "Hot Pink", id = 135 },
		{ name = "Pfister Pink", id = 137 },
		{ name = "Lachs Pink", id = 136 },
		{ name = "Sonnenaufgangs Orange", id = 36 },
		{ name = "Orange", id = 38 },
		{ name = "Strahlendes Orange", id = 138 },
		{ name = "Gold", id = 99 },
		{ name = "Bronze", id = 90 },
		{ name = "Gelb", id = 88 },
		{ name = "Renn Gelb", id = 89 },
		{ name = "Tau Gelb", id = 91 },
		{ name = "Dunkles Grün", id = 49 },
		{ name = "Renn Grün", id = 50 },
		{ name = "Meer Grün", id = 51 },
		{ name = "Olive Grün", id = 52 },
		{ name = "Strahlendes Grün", id = 53 },
		{ name = "Benzin Grün", id = 54 },
		{ name = "Limetten Grün", id = 92 },
		{ name = "Mitternachts Blau", id = 141 },
		{ name = "Weltraum Blau", id = 61 },
		{ name = "Dunkles Blau", id = 62 },
		{ name = "Saxon Blau", id = 63 },
		{ name = "Blau", id = 64 },
		{ name = "Marine Blau", id = 65 },
		{ name = "Hafen Blau", id = 66 },
		{ name = "Diamant Blau", id = 67 },
		{ name = "Surfer Blau", id = 68 },
		{ name = "Tiefsee Blau", id = 69 },
		{ name = "Renn Blau", id = 73 },
		{ name = "Ultra Blau", id = 70 },
		{ name = "Leichtes Blau", id = 74 },
		{ name = "Schoko Braun", id = 96 },
		{ name = "Bison Braun", id = 101 },
		{ name = "Creeen Braun", id = 95 },
		{ name = "Feltzer Braun", id = 94 },
		{ name = "Ahorn Braun", id = 97 },
		{ name = "Buchenholz Braun", id = 103 },
		{ name = "Ocker Braun", id = 104 },
		{ name = "Sattel Braun", id = 98 },
		{ name = "Moos Braun", id = 100 },
		{ name = "Holzbuche Braun", id = 102 },
		{ name = "Stroh Braun", id = 99 },
		{ name = "Sandiges Braun", id = 105 },
		{ name = "Gebleichtes Braun", id = 106 },
		{ name = "Schafter Lila", id = 71 },
		{ name = "Spinnaker Lila", id = 72 },
		{ name = "Mitternachts Lila", id = 142 },
		{ name = "Strahlendes Lila", id = 145 },
		{ name = "Cremig", id = 107 },
		{ name = "Eis Weiß", id = 111 },
		{ name = "Frost Weiß", id = 112 },
	},
	vehicleResprayOptionsMatte = {
		{ name = "Schwarz", id = 12 },
		{ name = "Grau", id = 13 },
		{ name = "Leichtes Grau", id = 14 },
		{ name = "Eis Weiß", id = 131 },
		{ name = "Blau", id = 83 },
		{ name = "Dark Blau", id = 82 },
		{ name = "Mitternachts Blau", id = 84 },
		{ name = "Mitternachts Lila", id = 149 },
		{ name = "Schafter Lila", id = 148 },
		{ name = "Rot", id = 39 },
		{ name = "Dunkles Rot", id = 40 },
		{ name = "Orange", id = 41 },
		{ name = "Gelb", id = 42 },
		{ name = "Limetten Grün", id = 55 },
		{ name = "Grün", id = 128 },
		{ name = "Wald Grün", id = 151 },
		{ name = "Unterholz Grün", id = 155 },
		{ name = "Olive", id = 152 },
		{ name = "Dunkle Erde", id = 153 },
		{ name = "Wüste", id = 154 },
	},
	vehicleResprayOptionsMetals = {
		{ name = "Gebürsteter Stahl", id = 117 },
		{ name = "Gebürsteter Schwarzer Stahl", id = 118 },
		{ name = "Gebürstetes Aluminium", id = 119 },
		{ name = "Pures Gold", id = 158 },
		{ name = "Gebürstetes Gold", id = 159 },
		{ name = "Chrom", id = 120 },
	},
	vehicleResprayOptionsChameleon = {
		{ name = "Eloxiert Rot", id = 161 },
		{ name = "Eloxiert Wine", id = 162 },
		{ name = "Eloxiert Lila", id = 163 },
		{ name = "Eloxiert Blau", id = 164 },
		{ name = "Eloxiert Grün", id = 165 },
		{ name = "Eloxiert Lime", id = 166 },
		{ name = "Eloxiert Kupfer", id = 167 },
		{ name = "Eloxiert Bronze", id = 168 },
		{ name = "Eloxiert Champagner", id = 169 },
		{ name = "Eloxiert Gold", id = 170 },
		{ name = "Grün/Blau Flip", id = 171 },
		{ name = "Grün/Rot Flip", id = 172 },
		{ name = "Grün/Braun Flip", id = 173 },
		{ name = "Grün/Türkis Flip", id = 174 },
		{ name = "Grün/Lila Flip", id = 175 },
		{ name = "Teal/Lila Flip", id = 176 },
		{ name = "Türkis/Rot Flip", id = 177 },
		{ name = "Türkis/Lila Flip", id = 178 },
		{ name = "Cyan/Lila Flip", id = 179 },
		{ name = "Blau/Pink Flip", id = 180 },
		{ name = "Blau/Grün Flip", id = 181 },
		{ name = "Lila/Rot Flip", id = 182 },
		{ name = "Pruple/Grün Flip", id = 183 },
		{ name = "Magenta/Grün Flip", id = 184 },
		{ name = "Magenta/Yellow Flip", id = 185 },
		{ name = "Burgundy/Grün Flip", id = 186 },
		{ name = "Magenta/Cyan Flip", id = 187 },
		{ name = "Kupfer/Lila Flip", id = 188 },
		{ name = "Magenta/Orange Flip", id = 189 },
		{ name = "Rot/Orange Flip", id = 190 },
		{ name = "Orange/Lila Flip", id = 191 },
		{ name = "Orange/Blau Flip", id = 192 },
		{ name = "Weiß/Lila Flip", id = 193 },
		{ name = "Rot/Rainbow Flip", id = 194 },
		{ name = "Blau/Rainbow Flip", id = 195 },
		{ name = "Dark Grün Pearl", id = 196 },
		{ name = "Dark Teal Pearl", id = 197 },
		{ name = "Dark Blau Pearl", id = 198 },
		{ name = "Dark Lila Pearl", id = 199 },
		{ name = "Oil Slick Pearl", id = 200 },
		{ name = "Light Grün Pearl", id = 201 },
		{ name = "Light Blau Pearl", id = 202 },
		{ name = "Light Lila Pearl", id = 203 },
		{ name = "Light Pink Pearl", id = 204 },
		{ name = "Off Weiß Pearl", id = 205 },
		{ name = "Pink Pearl", id = 206 },
		{ name = "Yellow Pearl", id = 207 },
		{ name = "Grün Pearl", id = 208 },
		{ name = "Blau Pearl", id = 209 },
		{ name = "Cremig Pearl", id = 210 },
		{ name = "Weiß Prismatisch", id = 211 },
		{ name = "Graphite Prismatisch", id = 212 },
		{ name = "Dark Blau Prismatisch", id = 213 },
		{ name = "Dark Lila Prismatisch", id = 214 },
		{ name = "Hot Pink Prismatisch", id = 215 },
		{ name = "Dark Rot Prismatisch", id = 216 },
		{ name = "Dark Grün Prismatisch", id = 217 },
		{ name = "Schwarz Prismatisch", id = 218 },
		{ name = "Schwarz Oil Spill", id = 219 },
		{ name = "Schwarz Rainbow", id = 220 },
		{ name = "Schwarz Holografisch", id = 221 },
		{ name = "Weiß Holografisch", id = 222 },
		{ name = "Monochrom", id = 223 },
		{ name = "Nacht / Tag", id = 224 },
		{ name = "Verlierer 2", id = 225 },
		{ name = "Sprunk Extreme", id = 226 },
		{ name = "Vice City", id = 227 },
		{ name = "Synthwave", id = 228 },
		{ name = "Four Seasons", id = 229 },
		{ name = "Maisonette 9 Throwback", id = 230 },
		{ name = "Bubblegum", id = 231 },
		{ name = "Full Rainbow", id = 232 },
		{ name = "Sunsets", id = 233 },
		{ name = "The Seven", id = 234 },
		{ name = "Kamen Rider", id = 235 },
		{ name = "Chrome Abberation", id = 236 },
		{ name = "Its Christmas", id = 237 },
		{ name = "Temperature", id = 238 },
		{ name = "Haos Special Works", id = 239 },
		{ name = "Electro", id = 240 },
		{ name = "Monika", id = 241 },
		{ name = "Fubuki", id = 242 }
	},
}